=== ABDonegan/obiesource.github.io/src/member.schema.json
{
  "$comment": "This is the JSON Schema (http://json-schema.org) for a club member file in the members/ directory. It can be used to validate the members files or just for good autocomplete and hints in editors like VS Code.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "VSCode uses this to provide autocomplete for the schema (see https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json)",
      "type": "string"
    },
    "status": {
      "description": "Whether you're a member, a club officer, or an alum",
      "enum": ["member", "officer", "alum"],
      "default": "member"
    },
    "name": { "description": "Your name", "type": "string" },
    "pronouns": { "description": "Your pronouns", "type": "string" },
    "class": {
      "description": "Your class year. For example, if you'll graduate in 2027, this should be \"'27\".",
      "type": "string",
      "default": "'27",
      "examples": ["'24", "'25", "'26", "'27", "'28", "'29", "'30", "'31"]
    },
    "socials": {
      "description": "An array with links to any social media accounts you want to share",
      "type": "array",
      "items": { "type": "string" }
    },
    "bio": {
      "description": "Write something about yourself here!",
      "type": "string",
      "examples": [
        "Hello! I'm a 6th year Geography major with a concentration in Computer Science. I like sticks and rocks and mud."
      ]
    },
    "projects": {
      "description": "An array of projects you've worked on or are working on that you want to share",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "website": {
            "type": "string"
          }
        },
        "required": ["name", "description", "website"],
        "minProperties": 1
      }
    }
  },
  "required": ["name"],
  "additionalProperties": false
}

=== ABDonegan/obiesource.github.io/members/kai.json
{
	"name": "Kai Monno",
	"pronouns": "he/ him/ his",
	"class": "'26",
	"socials": [
		"https://www.instagram.com/kaimonno/",
		"https://www.facebook.com/kai.monno.92/"
	],
	"bio": "Hello, I am Kai Monno I am a first year computer science major. I plan to get very involved in the obiesource club!",
	"projects": [
		{
			"name": "My Github",
			"description": "This is my github.",
			"website": "https://github.com/KaiMonno"
		}
		
	]
}

=== ABDonegan/obiesource.github.io/members/rehwinkel.json
{
    "name": "William Rehwinkel",
    "pronouns": "he/him/his",
    "class": "'24",
    "socials": [
        "https://www.facebook.com/william.rehwinkel.58",
        "https://koyu.space/@fiskfan1999",
        "https://www.instagram.com/fiskfan1999/",
        "https://www.youtube.com/channel/UCPnda1E2qCD7lA1XvDs7Xvg",
        "https://video.ploud.jp/c/william_rehwinkel_pipe_organ/videos"
    ],
    "bio": "Hello! I'm a 3rd year double-degree student majoring in Computer Science and the Pipe Organ. I am from the New York/New Jersey area. In addition to computer programming my passion is playing the organ, and I operate a Youtube channel where I upload recordings of the organs here on campus! My most favorite thing about programming is web-design, and have recently got into static website hosting using javascript! If you would like to learn more about the organ, feel free to follow my Instagram page (@FiskFan1999), where I post memes and other funny content about the pipe organ and early music.",
    "projects": [
        {
            "name": "wvlist",
            "description": "Catalogue of compositions with community submissions",
            "website": "https://wvlist.net"
        }
    ]
}

=== ABDonegan/obiesource.github.io/src/members/nghinguyen.json
{
  "name": "Nghi Nguyen",
  "pronouns": "he/him/his",
  "class": "'24",
  "socials": ["https://github.com/nghi01"],
  "bio": "Hello! I'm a 3rd year Computer Science major, Philosophy Minor. My favorite game is Dark Souls III, favorite book is Kokoro by Natsume Souseki. I also like touching grass.",
  "projects": [
    {
      "name": "MazeGame",
      "description": "I made a maze exploration game with some friends in Unreal Engine. Still under development though.",
      "website": "https://github.com/bucket420/MazeGame"
    }
  ]
}

=== ABDonegan/obiesource.github.io/src/members/toker.json
{
  "$schema": "../member.schema.json",
  "name": "Ben Toker",
  "status": "officer",
  "pronouns": "he/him/his",
  "class": "Class of 2026",
  "socials": ["btoker.dev"],
  "bio": "Hey! I'm Ben, president of ObieSource! I love Rust, C, Java, and (sometimes) Python. I love to read, play jazz guitar, and make coffee! Let's make some cool stuff ^_^",
  "projects": [
    {
      "name": "flowst",
      "description": "A pomodoro study tool built in rust!",
      "website": "https://github.com/ben-toker/flowst"
    }
  ]
}

=== ABDonegan/obiesource.github.io/src/members/nelson.json
{
  "$schema": "../member.schema.json",
  "name": "Ajai Nelson",
  "status": "officer",
  "pronouns": "he/him/his",
  "class": "'25",
  "socials": ["https://github.com/AjaiKN/", "https://ajai.dev/"],
  "bio": "Hi, I'm Ajai! My hobbies include worrying that someone will ask me to write a description of myself.",
  "projects": [
    {
      "name": "OPrestissimo",
      "description": "A student-run alternative course catalog / schedule of classes for Oberlin. It was made 10 years ago by other students, and I'm the current maintainer. Let me know if you want to help!",
      "website": "https://oprestissimo.com/"
    }
  ]
}
